<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Edit_Teacher.aspx.cs" Inherits="Edit_Teacher" %>

<!doctype html>
<html>
<head runat="server">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0; maximum-scale=2.0; user-scalable=0;">

    <title>FP 2.0 - Edit Teacher</title>

    <link href="../../CSS/StaffPages.css" rel="stylesheet" media="screen" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="shortcut icon" type="image/png" href="../../Media/faviconFP.png" />

    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
</head>

<body>
    <form id="EMS_Form" runat="server">

        <%--Header information--%>
        <header class="headerTop no-print"><a style="float: left; padding-top: 2px;">Finance Park 2.0</a><a style="float: right; padding-right: 30px; padding-top: 2px;"><asp:Label ID="lblHeaderSchoolName" Text="School Name Here" runat="server"></asp:Label></a></header>

        <%--Navigation bar--%>
        <div id="nav-placeholder">
        </div>

        <script>
            $(function () {
                $("#nav-placeholder").load("../../nav.html");
            });
        </script>

        <%--Content--%>
        <div class="content">
            <h2 class="h2">Edit Teacher</h2>
            <h3 class="no-print">This page displays all teachers in the database. Select the school the teacher belongs to from the drop down menu below.
                <%--The password criteria is the school name + county name (Example: gullettmanatee) --%>
            </h3>
            <p>School Name:</p>
            <asp:DropDownList CssClass="ddl" ID="ddlSchoolName" runat="server" AutoPostBack="true" OnSelectedIndexChanged="ddlSchoolName_SelectedIndexChanged"></asp:DropDownList> &ensp;<asp:Label ID="lblError" runat="server" ForeColor="Red" Font-Size="X-Large"></asp:Label>            
            <p>Search by Teacher Name:</p>
            <asp:TextBox ID="tbSearch" runat="server" CssClass="textbox" Width="200px"></asp:TextBox> <asp:Button ID="btnSearch" runat="server" CssClass="button" text="Search" OnClick="btnSearch_Click"/>
            <br /><br />
            <asp:Button ID="btnRefresh" runat="server" CssClass="button" Text="Show All Teachers" OnClick="btnRefresh_Click" />
            <br /><br />

            <%--Optional Gridview--%>
            <div id="divTeachers" runat="server" visible="true">
                <%-- "  --%>
                <asp:GridView ID="dgvTeachers" runat="server" AutoGenerateColumns="False" AutoGenerateEditButton="True" AutoGenerateDeleteButton="true" DataKeyNames="ID" CellPadding="5" Height="50" PageSize="11" AllowPaging="True" ShowHeaderWhenEmpty="True" Font-Size="Medium" Visible="true" OnRowEditing="dgvTeachers_RowEditing" OnRowCancelingEdit="dgvTeachers_RowCancelingEdit" OnRowUpdating="dgvTeachers_RowUpdating" OnRowDataBound="dgvTeachers_RowDataBound" OnPageIndexChanging="dgvTeachers_PageIndexChanging" OnRowDeleting="dgvTeachers_RowDeleting" PagerStyle-CssClass="pager" HeaderStyle-CssClass="header" RowStyle-CssClass="rows">
                    <Columns>
                        <asp:BoundField DataField="ID" HeaderText="ID" Visible="false" />
                        <asp:TemplateField HeaderText="School Name">
                            <ItemTemplate>
                                <asp:Label id="lblSchoolNameDGV" runat="server" Text='<%#Bind("schoolID") %>' Visible="false"></asp:Label>
                                <asp:DropDownList CssClass="ddl" ID="ddlSchoolNameDGV" runat="server" Width="200px" AutoPostBack="true" ReadOnly="false">
                                </asp:DropDownList>
                            </ItemTemplate>                         
                        </asp:TemplateField>
                        <asp:TemplateField Headertext="First Name">
                            <ItemTemplate>
                                <asp:TextBox ID="tbFirstNameDGV" runat="server" Width="80px" Text='<%#Bind("firstName") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Last Name">
                            <ItemTemplate>
                                <asp:TextBox ID="tbLastNameDGV" runat="server" Width="80px" Text='<%#Bind("lastName") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Teacher <br/> Email">
                            <ItemTemplate>
                                <asp:TextBox ID="tbEmailDGV" runat="server" Width="200px" Text='<%#Bind("email") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Password" Visible="true">
                            <ItemTemplate>
                                <asp:TextBox ID="tbPasswordDGV" runat="server" Width="80px" Text='<%#Bind("password") %>' Visible="true" CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Contact <br/> Teacher?">
                            <ItemTemplate>
                                <asp:CheckBox ID="chkContactDGV" runat="server" Checked='<%#Bind("contact") %>' />
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="currVisitDate" HeaderText="Current<br />Visit Date" DataFormatString="{0: MM/dd/yyyy } " HtmlEncode="false" />
                        <asp:BoundField DataField="prevVisitDate" HeaderText="Previous<br />Visit Date" DataFormatString="{0: MM/dd/yyyy } " HtmlEncode="false" />
                    </Columns>
                </asp:GridView>
            </div>
        </div>

        <asp:HiddenField ID="hfCurrentVisitID" runat="server" />
        <asp:HiddenField ID="hfTeachers" runat="server" />

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="Scripts.js"></script>
        <script>
            /* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
            $(".sub-menu ul").hide();
            $(".sub-menu a").click(function () {
                $(this).parent(".sub-menu").children("ul").slideToggle("100");
                $(this).find(".right").toggleClass("fa-caret-up fa-caret-down");
            });
        </script>

        <%--Delete confirmation--%>
        <script>
            jQuery("a").filter(function () {
                return this.innerHTML.indexOf("Delete") == 0;
            }).click(function () {
                return confirm("Are you sure you want to delete this teacher?");
            });
        </script>

        <asp:SqlDataSource ID="Review_sds" runat="server"></asp:SqlDataSource>
    </form>
</body>
</html>
