<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Edit_Job.aspx.cs" Inherits="Edit_Job" %>

<!doctype html>
<html>
<head runat="server">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0; maximum-scale=2.0; user-scalable=0;">

    <title>FP 2.0 - Edit Job</title>

    <link href="../../CSS/StaffPages.css" rel="stylesheet" media="screen" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="shortcut icon" type="image/png" href="../../Media/faviconFP.png" />

    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
</head>

<body>
    <form id="EMS_Form" runat="server">

        <%--Header information--%>
        <header class="headerTop no-print"><a style="float: left; padding-top: 2px;">Finance Park 2.0</a><a style="float: right; padding-right: 30px; padding-top: 2px;"><asp:Label ID="headerSchoolName_lbl" Text="School Name Here" runat="server"></asp:Label></a></header>

        <%--Navigation bar--%>
        <div id="nav-placeholder">
        </div>

        <script>
            $(function () {
                $("#nav-placeholder").load("../../nav.html");
            });
        </script>

        <%--Content--%>
        <div class="content">
            <h2 class="h2">Edit Job</h2>
            <h3>This page allows you to edit existing jobs.
                <br />
                <br />
                Select a specific job from the drop down menu or search for it using the search textbox and button.
            </h3>
            <p>Job Title:</p>
            <asp:DropDownList ID="jobTitle_ddl" runat="server" CssClass="ddl" AutoPostBack="true" ></asp:DropDownList>&ensp;<asp:Label ID="error_lbl" runat="server" Font-Bold="true" Font-Size="X-Large" ForeColor="Red"></asp:Label>
            <p>Type in Job Title:</p>
            <asp:TextBox ID="search_tb" runat="server" CssClass="textbox"></asp:TextBox>&ensp;<asp:Button ID="submit_btn" runat="server" Text="Search" CssClass="button" OnClick="submit_btn_Click" />
            <br />

            <%--Optional Gridview--%>
            <div id="jobs_div" runat="server" visible="false">
                <asp:GridView ID="jobs_dgv" runat="server" AutoGenerateColumns="False" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" DataKeyNames="ID" CellPadding="5" Height="50" AllowPaging="True" ShowHeaderWhenEmpty="True" Font-Size="Medium" OnRowEditing="jobs_dgv_RowEditing" OnRowCancelingEdit="jobs_dgv_RowCancelingEdit" OnRowUpdating="jobs_dgv_RowUpdating" OnRowDataBound="jobs_dgv_RowDataBound" OnPageIndexChanging="jobs_dgv_PageIndexChanging" PagerStyle-CssClass="pager" HeaderStyle-CssClass="header" RowStyle-CssClass="rows" Visible="true"> 
                    <AlternatingRowStyle BackColor="#99CCFF" />
                    <Columns>
                        <asp:BoundField DataField="ID" HeaderText="ID" Visible="false" />
                        <asp:TemplateField HeaderText="Job Title">
                            <ItemTemplate>
                                <asp:Textbox ID="jobTitleDGV_lbl" runat="server" Text='<%#Bind("jobTitle") %>' CssClass="textbox" Visible="true"></asp:Textbox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Business">
                            <ItemTemplate>
                               <asp:Label ID="businessNameDGV_lbl" runat="server" Text='<%#Bind("business") %>' Visible="false"></asp:Label>
                               <asp:DropDownList ID="businessNameDGV_ddl" runat="server" CssClass="ddl" AutoPostBack="true"></asp:DropDownList>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Education <br /> Background">
                            <ItemTemplate>
                                <asp:Label ID="educationBGDGV_lbl" runat="server" Text='<%#Bind("educationBG") %>' Visible="false" ReadOnly="true"></asp:Label>
                                <asp:DropDownList ID="educationBGDGV_ddl" runat="server" CssClass="ddl" AutoPostBack="true">
                                    <asp:ListItem>Associate's Degree</asp:ListItem>
                                    <asp:ListItem>Bachelor's Degree</asp:ListItem>
                                    <asp:ListItem>Master's Degree</asp:ListItem>
                                    <asp:ListItem>High School Diploma</asp:ListItem>
                                    <asp:ListItem>Trade/Vocational School</asp:ListItem>
                                </asp:DropDownList>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Job Duties">
                            <ItemTemplate>
                                <asp:Label ID="jobDutiesDGV_lbl" runat="server" Visible="false" Text='<%#Bind("jobDuties") %>'></asp:Label>
                                <textarea id="jobDutiesDGV_tb" runat="server" class="textbox" ></textarea>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Educational <br /> Debt">
                            <ItemTemplate>
                                <asp:Textbox ID="edDebtDGV_lbl" runat="server" Text='<%#Bind("edDebt") %>' CssClass="textbox" Visible="true"></asp:Textbox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Advancement">
                            <ItemTemplate>
                                <asp:Label ID="advancementDGV_lbl" runat="server" Visible="false" Text='<%#Bind("advancement") %>'></asp:Label>
                                <textarea id="advancementDGV_tb" runat="server" class="textbox" ></textarea>
                            </ItemTemplate>
                        </asp:TemplateField>
                    </Columns>
                </asp:GridView>
            </div>
        </div>

        <asp:HiddenField ID="currentVisitID_hf" runat="server" />

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="Scripts.js"></script>
        <script>
            /* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
            $(".sub-menu ul").hide();
            $(".sub-menu a").click(function () {
                $(this).parent(".sub-menu").children("ul").slideToggle("100");
                $(this).find(".right").toggleClass("fa-caret-up fa-caret-down");
            });
        </script>

        <asp:SqlDataSource ID="Review_sds" runat="server"></asp:SqlDataSource>
    </form>
</body>
</html>
