<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Edit_Sponsor.aspx.cs" Inherits="Edit_Sponsor" %>

<!doctype html>
<html>
<head runat="server">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0; maximum-scale=2.0; user-scalable=0;">

    <title>FP 2.0 - Edit Sponsor</title>

    <link href="../../CSS/StaffPages.css" rel="stylesheet" media="screen" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="shortcut icon" type="image/png" href="../../Media/faviconFP.png" />

    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
</head>

<body>
    <form id="EMS_Form" runat="server">

        <%--Header information--%>
        <header class="headerTop no-print"><a style="float: left; padding-top: 2px;">Finance Park 2.0</a><a style="float: right; padding-right: 30px; padding-top: 2px;"><asp:Label ID="lblHeaderSchoolName" Text="School Name Here" runat="server"></asp:Label></a></header>

        <%--Navigation bar--%>
        <div id="nav-placeholder">
        </div>

        <script>
            $(function () {
                $("#nav-placeholder").load("../../nav.html");
            });
        </script>

        <%--Content--%>
        <div class="content">
            <h2 class="h2">Edit Sponsor</h2>
            <h3>The page allows you to edit existing sponsors.
            </h3>
            <p>Sponsor Name:</p>
            <asp:DropDownList ID="ddlSponsorName" runat="server" CssClass="ddl" AutoPostBack="true" OnSelectedIndexChanged="ddlSponsorName_SelectedIndexChanged"></asp:DropDownList>&ensp;<asp:Label ID="lblError" runat="server" Font-Bold="true" Font-Size="X-Large" ForeColor="Red"></asp:Label>
            <br /><br />

            <%--Optional Gridview--%>
            <div id="sponsors_div" runat="server" visible="true">
                <asp:GridView ID="dgvSponsors" runat="server" AutoGenerateColumns="False" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true" DataKeyNames="ID" CellPadding="5" Height="50" AllowPaging="True" ShowHeaderWhenEmpty="True" Font-Size="Medium" OnRowEditing="dgvSponsors_RowEditing" OnRowCancelingEdit="dgvSponsors_RowCancelingEdit" OnRowUpdating="dgvSponsors_RowUpdating" OnRowDataBound="dgvSponsors_RowDataBound" OnPageIndexChanging="dgvSponsors_PageIndexChanging" OnRowDeleting="dgvSponsors_RowDeleting" PagerStyle-CssClass="pager" HeaderStyle-CssClass="header" RowStyle-CssClass="rows" Visible="true"> 
                    <Columns>
                        <asp:BoundField DataField="ID" HeaderText="ID" Visible="false" />
                        <asp:TemplateField HeaderText="Sponsor Name">
                            <ItemTemplate>
                               <asp:TextBox ID="tbSponsorNameDGV" runat="server" ReadOnly="false" Text='<%#Bind("sponsorName") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Business #1">
                            <ItemTemplate>
                                <asp:Label ID="lblBusinessName1DGV" runat="server" Text='<%#Bind("businessID") %>' Visible="false"></asp:Label>
                                <asp:DropDownList CssClass="ddl" ID="ddlBusinessName1DGV" runat="server" AutoPostBack="true" readonly="false"></asp:DropDownList>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Business #2">
                            <ItemTemplate>
                                <asp:Label ID="lblBusinessName2DGV" runat="server" Text='<%#Bind("businessID2") %>' Visible="false"></asp:Label>
                                <asp:DropDownList CssClass="ddl" ID="ddlBusinessName2DGV" runat="server" AutoPostBack="true" readonly="false"></asp:DropDownList>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Business #3">
                            <ItemTemplate>
                                <asp:Label ID="lblBusinessName3DGV" runat="server" Text='<%#Bind("businessID3") %>' Visible="false"></asp:Label>
                                <asp:DropDownList CssClass="ddl" ID="ddlBusinessName3DGV" runat="server" AutoPostBack="true" readonly="false"></asp:DropDownList>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Business #4">
                            <ItemTemplate>
                                <asp:Label ID="lblBusinessName4DGV" runat="server" Text='<%#Bind("businessID4") %>' Visible="false"></asp:Label>
                                <asp:DropDownList CssClass="ddl" ID="ddlBusinessName4DGV" runat="server" AutoPostBack="true" readonly="false"></asp:DropDownList>
                            </ItemTemplate>
                        </asp:TemplateField>                       
                        <asp:ImageField DataImageUrlField="logoPath" ControlStyle-Width="100" ControlStyle-Height="100" HeaderText="Logo" ReadOnly="true">
                            <ControlStyle Height="100px" Width="100px"></ControlStyle>
                        </asp:ImageField>
                    </Columns>
                </asp:GridView>
            </div>
        </div>

        <asp:HiddenField ID="hfCurrentVisitID" runat="server" />

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="Scripts.js"></script>
        <script>
            /* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
            $(".sub-menu ul").hide();
            $(".sub-menu a").click(function () {
                $(this).parent(".sub-menu").children("ul").slideToggle("100");
                $(this).find(".right").toggleClass("fa-caret-up fa-caret-down");
            });
        </script>

        <asp:SqlDataSource ID="Review_sds" runat="server"></asp:SqlDataSource>
    </form>
</body>
</html>
