<%@ Page Language="C#" AutoEventWireup="true" CodeFile="Edit_School.aspx.cs" Inherits="Edit_School" %>

<!doctype html>
<html>
<head runat="server">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0; maximum-scale=2.0; user-scalable=0;">

    <title>FP 2.0 - Edit School</title>

    <link href="../../CSS/StaffPages.css" rel="stylesheet" media="screen" type="text/css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
    <link rel="shortcut icon" type="image/png" href="../../Media/faviconFP.png" />

    <script src="https://code.jquery.com/jquery-1.10.2.js"></script>
</head>

<body>
    <form id="EMS_Form" runat="server">

        <%--Header information--%>
        <header class="headerTop no-print"><a style="float: left; padding-top: 2px;">Finance Park 2.0</a><a style="float: right; padding-right: 30px; padding-top: 2px;"><asp:Label ID="lblHeaderSchoolName" Text="School Name Here" runat="server"></asp:Label></a></header>

        <%--Navigation bar--%>
        <div id="nav-placeholder">
        </div>

        <script>
            $(function () {
                $("#nav-placeholder").load("../../nav.html");
            });
        </script>

        <%--Content--%>
        <div class="content">
            <h2 class="h2">Edit School</h2>
            <h3 class="no-print">This page will allow you to edit a school in the database. 
                <br />
                <br />
                Use the drop down menu below to view a specific school. You can also use the textbox under that to search for a school name.
            </h3>
            <p>School Name:</p>
            <asp:DropDownList ID="ddlSchoolName" runat="server" CssClass="ddl" AutoPostBack="true" OnSelectedIndexChanged="ddlSchoolName_SelectedIndexChanged"></asp:DropDownList>&ensp;<asp:Label ID="lblError" runat="server" ForeColor="Red" Font-Bold="true" Font-Size="X-Large"></asp:Label>
            <p>Type in School Name:</p>
            <asp:TextBox ID="tbSearch" runat="server" CssClass="textbox"></asp:TextBox> &nbsp;&nbsp; <asp:Button ID="btnSearch" runat="server" CssClass="button" text="Search" OnClick="btnSearch_Click"/>     
            <br /><br />            
            <asp:Button ID="btnRefresh" runat="server" CssClass="button" text="Show All Schools" OnClick="btnRefresh_Click"/>
            <br /><br />

            <%--Print Out Table--%>
            <div class="gridviewDiv">
                <asp:GridView ID="dgvSchool" runat="server" AutoGenerateColumns="False" PageSize="10" AutoGenerateEditButton="True" AutoGenerateDeleteButton="false" DataKeyNames="ID" CellPadding="3" AllowPaging="True" ShowHeaderWhenEmpty="True" Font-Size="Medium" Visible="true" OnRowCancelingEdit="dgvSchool_RowCancelingEdit" OnRowEditing="dgvSchool_RowEditing" OnRowUpdating="dgvSchool_RowUpdating" OnPageIndexChanging="dgvSchool_PageIndexChanging" PagerStyle-CssClass="pager" HeaderStyle-CssClass="header" RowStyle-CssClass="rows">
                    <Columns>
                        <asp:BoundField DataField="ID" HeaderText="ID" Visible="false" />
                        <%--<asp:BoundField DataField="schoolName" HeaderText="School Name" Visible="true" ReadOnly="true" />--%>
                        <asp:TemplateField HeaderText="School Name">
                            <ItemTemplate>
                                <asp:Textbox id="tbSchoolNameDGV" runat="server" Text='<%#Bind("schoolName") %>' Visible="true" CssClass="textbox" Width="200px"></asp:Textbox>
                            </ItemTemplate>                         
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Address">
                             <ItemTemplate>
                                 <asp:TextBox ID="tbAddressDGV" runat="server" Width="100px" Text='<%#Bind("address") %>' CssClass="textbox"></asp:TextBox>
                             </ItemTemplate>
                         </asp:TemplateField>
                         <asp:TemplateField HeaderText="City">
                             <ItemTemplate>
                                 <asp:TextBox ID="tbCityDGV" runat="server" Width="100px" Text='<%#Bind("city") %>' CssClass="textbox"></asp:TextBox>
                             </ItemTemplate>
                         </asp:TemplateField>
                         <asp:TemplateField HeaderText="Zip Code">
                             <ItemTemplate>
                                 <asp:TextBox ID="tbZipDGV" runat="server" Width="30px" Text='<%#Bind("zip") %>' TextMode="Number" CssClass="textbox"></asp:TextBox>
                             </ItemTemplate>
                         </asp:TemplateField>
                         <asp:TemplateField HeaderText="County">
                             <ItemTemplate>
                                 <asp:TextBox ID="tbCountyDGV" runat="server" Width="100px" Text='<%#Bind("county") %>' CssClass="textbox"></asp:TextBox>
                             </ItemTemplate>
                         </asp:TemplateField>
                        <asp:TemplateField HeaderText="Principal </br> First Name" >
                            <ItemTemplate>
                                <asp:TextBox ID="tbPrincipalFirstDGV" runat="server" Width="80px" Text='<%#Bind("principalFirst") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>                         
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Principal </br> Last Name">
                            <ItemTemplate>
                                <asp:TextBox ID="tbPrincipalLastDGV" runat="server" Width="80px" Text='<%#Bind("principalLast") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>                         
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Administrator </br> Email">
                            <ItemTemplate>
                                <asp:TextBox ID="tbAdministratorEmailDGV" runat="server" Width="200px" Text='<%#Bind("administratorEmail") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField> 
                        <asp:TemplateField HeaderText="Phone #">
                            <ItemTemplate>
                                <asp:TextBox ID="tbPhoneDGV" runat="server" Width="95px" Text='<%#Bind("phone") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>                         
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Hours">
                            <ItemTemplate>
                                <asp:TextBox ID="tbHoursDGV" runat="server" Width="70px" Text='<%#Bind("schoolHours") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>                         
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="School Type">
                            <ItemTemplate>
                                <asp:Label ID="lblSchoolTypeDGV" runat="server" Text='<%#Bind("schoolType") %>' Visible="false"></asp:Label>
                                <asp:DropDownList CssClass="ddl" ID="ddlSchoolTypeDGV" runat="server" AutoPostBack="true" >
                                        <asp:ListItem>Public</asp:ListItem>
                                        <asp:ListItem>Private</asp:ListItem>
                                        <asp:ListItem>Charter</asp:ListItem>
                                        <asp:ListItem>OC</asp:ListItem>
                                        <asp:ListItem>Religious</asp:ListItem>
                                </asp:DropDownList>
                            </ItemTemplate>                         
                        </asp:TemplateField>                                                                  
                        <asp:TemplateField HeaderText="Liaison">
                            <ItemTemplate>
                                <asp:TextBox ID="tbLiaisonNameDGV" runat="server" Width="100px" Text='<%#Bind("liaisonName") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:TemplateField HeaderText="Notes">
                            <ItemTemplate>
                                <asp:TextBox ID="tbNotesDGV" runat="server" Width="200px" Text='<%#Bind("notes") %>' CssClass="textbox"></asp:TextBox>
                            </ItemTemplate>
                        </asp:TemplateField>
                        <asp:BoundField DataField="currentVisitDate" HeaderText="Current Visit Date" Visible="true" DataFormatString="{0: MM/dd/yyyy } " ReadOnly="true" />
                        <asp:BoundField DataField="previousVisitDate" HeaderText="Previous Visit Date" Visible="true" DataFormatString="{0: MM/dd/yyyy } " ReadOnly="true" /> 
                    </Columns>
                </asp:GridView>
            </div>
        </div>

        <asp:HiddenField ID="hfVisitDate" runat="server" />
        <asp:HiddenField ID="hfVisitDateUpdate" runat="server" />

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="Scripts.js"></script>
        <script>
            /* Loop through all dropdown buttons to toggle between hiding and showing its dropdown content - This allows the user to have multiple dropdowns without any conflict */
            $(".sub-menu ul").hide();
            $(".sub-menu a").click(function () {
                $(this).parent(".sub-menu").children("ul").slideToggle("100");
                $(this).find(".right").toggleClass("fa-caret-up fa-caret-down");
            });
        </script>
        
        <%--Delete confirmation--%>
        <%--<script>
            jQuery("a").filter(function () {
                return this.innerHTML.indexOf("Delete") == 0;
            }).click(function () {
                return confirm("Are you sure you want to delete this teacher?");
            });
        </script>--%>

        <asp:SqlDataSource ID="Review_sds" runat="server"></asp:SqlDataSource>
        <asp:SqlDataSource ID="print_sds" runat="server"></asp:SqlDataSource>
    </form>
</body>
</html>
